### ISSUE TITLE
0.3-CUDA10 - rare class mining does not exist

### ISSUE THREAD

**Issue by mihsamusev** [ahrnbom/strudl#15]
Hi,
The API function `/jobs/rare_class_mining` exists only in _master_ and not in _0.3CUDA-10_
https://github.com/ahrnbom/strudl/blob/b0dc1d5232dbba42015458ea8da21c7c25d519a6/strudl.yaml#L650

**Comment by ahrnbom** [comment]
_master_ is the current unstable build. Rare class mining isn't fully implemented yet. If you want a (somewhat) stable build, you should use one of our releases.
